SetColumns(0);
load "src/paper_data.m";

ReplaceAllStrings := function(s, old, new)
    if old eq "" then
        return s;
    end if;

    out := "";
    rest := s;
    pos := Position(rest, old);
    while pos ne 0 do
        if pos gt 1 then
            out cat:= rest[1..pos - 1];
        end if;
        out cat:= new;
        start := pos + #old;
        if start le #rest then
            rest := rest[start..#rest];
            pos := Position(rest, old);
        else
            rest := "";
            pos := 0;
        end if;
    end while;

    return out cat rest;
end function;

IsDigitChar := function(c)
    return c ge "0" and c le "9";
end function;

ReadDigitToken := function(s, i)
    j := i;
    while j le #s and IsDigitChar(s[j]) do
        j +:= 1;
    end while;
    return s[i..j - 1], j;
end function;

BraceScriptsInLatexMath := function(s)
    out := "";
    i := 1;
    while i le #s do
        c := s[i];
        if (c eq "_" or c eq "^") and i lt #s and s[i + 1] ne "{" then
            out cat:= c cat "{";
            i +:= 1;
            while i le #s and (IsDigitChar(s[i]) or (s[i] ge "a" and s[i] le "z") or
                (s[i] ge "A" and s[i] le "Z")) do
                out cat:= s[i];
                i +:= 1;
            end while;
            out cat:= "}";
            continue;
        end if;
        out cat:= c;
        i +:= 1;
    end while;
    return out;
end function;

LatexTypeString := function(s)
    return "$" cat BraceScriptsInLatexMath(s) cat "$";
end function;

LatexWedgeString := function(s)
    out := "";
    i := 1;
    while i le #s do
        if s[i] eq "e" and i lt #s and IsDigitChar(s[i + 1]) then
            digits, j := ReadDigitToken(s, i + 1);
            out cat:= "e_{" cat digits cat "}";
            i := j;
            continue;
        end if;

        if s[i] eq "^" then
            out cat:= " \\wedge ";
            i +:= 1;
            continue;
        end if;

        out cat:= s[i];
        i +:= 1;
    end while;

    return "$" cat out cat "$";
end function;

PrintGeometricOrbitTable := procedure(n)
    F := GF(5);
    data := GeometricOrbitDataNLe7(F, n);

    print "";
    print "\\paragraph{$n=" cat Sprint(n) cat "$.}";
    print "\\begin{longtable}{@{}c p{0.22\\textwidth} p{0.29\\textwidth} p{0.29\\textwidth}@{}}";
    print "\\toprule";
    print "No. & Type & $\\omega_1$ & $\\omega_2$ \\\\";
    print "\\midrule";
    print "\\endfirsthead";
    print "\\toprule";
    print "No. & Type & $\\omega_1$ & $\\omega_2$ \\\\";
    print "\\midrule";
    print "\\endhead";
    print "\\midrule";
    print "\\multicolumn{4}{r}{Continued on next page}\\\\";
    print "\\midrule";
    print "\\endfoot";
    print "\\bottomrule";
    print "\\endlastfoot";

    for i in [1..#data] do
        print Sprint(i) cat " & "
            cat LatexTypeString(data[i]`name) cat " & "
            cat LatexWedgeString(data[i]`wedge1) cat " & "
            cat LatexWedgeString(data[i]`wedge2) cat " \\\\";
    end for;

    print "\\end{longtable}";
end procedure;

print "% This file is generated by magma/examples/generate_geometric_orbit_tables_tex.m.";
for n in [4..7] do
    PrintGeometricOrbitTable(n);
end for;
